config/routes.rb
Rails.application.routes.draw do

  mount API::Base => '/api'

  resources :contacts

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :phone_numbers, dependent: :destroy


  has_attached_file :avatar,
                    :styles => { :medium => "100x100>", :thumb => "50x50>" },
                    :default_url => "/assets/contacts/missing.gif",
                    :url  => "/assets/contacts/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/contacts/:id/:style/:basename.:extension"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  accepts_nested_attributes_for :phone_numbers, reject_if: lambda { |a| a[:phone].blank? }, allow_destroy: true

  validates :name, :last_name, :email, :user_id, presence: true
  validates :email, uniqueness: true

  def self.search(query)
    where("name like ? OR last_name like ?", "%#{query}%", "%#{query}%")
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:search]
      @contacts = Contact.where(user_id: current_user.id).search(params[:search])
    else
      @contacts = Contact.where(user_id: current_user.id)
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.create(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params) || @contact.phone_numbers.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :last_name, :email, :family, :friends, :coworker, :avatar, phone_numbers_attributes: [ :id, :phone, :_destroy ] )
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def new_fields_template(f,association,options={})
    options[:object]    ||= f.object.class.reflect_on_association(association).klass.new
    options[:partial]   ||= association.to_s.singularize+"_fields"
    options[:template]  ||= association.to_s+"_fields"
    options[:f]         ||= :f

    tmpl = content_tag :div,id: "#{options[:template]}" do
      tmpl = f.fields_for association,options[:object], child_index: "new_#{association}" do |b|
        render partial: options[:partial],locals: {f: b}
      end
    end
    tmpl = tmpl.gsub /(?<!\n)\n(?!\n)/, ' '
    return "<script> var #{options[:template]} = '#{tmpl.to_s}' </script>".html_safe
  end
  def add_child_button(name, association,target)
    content_tag :div,"<span>#{name}</span>".html_safe, class: "add_child btn btn-default", :"data-association" => association, target: target
  end
  def remove_child_button(name)
    content_tag :div,"<span>#{name}</span>".html_safe, style: "cursor:pointer",class: "remove_child btn btn-default"
  end
end

app/views/contacts/_form.html.haml
= form_for @contact, html: {class: "form-group", multipart: true} do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  %div
    %div
      = f.label :avatar
    = image_tag @contact.avatar.url(:thumb) if @contact.avatar_file_name != nil
    = f.file_field :avatar
  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :last_name
    = f.text_field :last_name, class: "form-control"
  .field
    = f.label :email
    = f.text_field :email, class: "form-control"
  .field
    = f.label "Type:"
    = f.label "Family"
    = f.check_box :family
    = f.label "Friends"
    = f.check_box :friends
    = f.label "Coworker"
    = f.check_box :coworker
  %div
    = add_child_button "Add Phone Number",:phone_numbers,"#tasks"
    = new_fields_template f, :phone_numbers
  #tasks
    = f.fields_for :phone_numbers do |builder|
      %div
        = render "phone_number_fields", :f => builder
  .actions
    = f.submit 'Save', class: "btn btn-default"

app/views/contacts/_phone_number_fields.html.haml
= f.hidden_field :_destroy, class: 'removable'
= f.label "Number"
= f.text_field :phone, class: "form-control"
= remove_child_button "Remove"

app/views/contacts/edit.html.haml
%div.col-md-4
%div.col-md-4
  %h1 Editing contact
  = render 'form'

  = link_to 'Show', @contact, class: "btn btn-default"
  \|
  = link_to 'Back', contacts_path, class: "btn btn-default"
%div.col-md-4

app/views/contacts/index.html.haml
%div.row
  %div.col-md-2
  %div.col-md-8
    %h1 Listing contacts
    %div.search
      = form_tag contacts_path, class: "form-group flex_f", method: :get do
        = search_field_tag :search, params[:search], placeholder: "Search", class: "form-control flex"
        = button_tag "Search", name: nil, class: "btn btn-default"
    %div.table-responsive
      %table.table.table-hover
        %thead
          %tr
            %th Avatar
            %th Name
            %th Last name
            %th Email
            %th Family
            %th Friends
            %th Coworker
            %th
            %th
            %th

        %tbody
          - @contacts.each do |contact|
            %tr
              %td= image_tag contact.avatar.url(:thumb)
              %td= contact.name
              %td= contact.last_name
              %td= contact.email
              %td= contact.family
              %td= contact.friends
              %td= contact.coworker
              %td= link_to 'Show', contact, class: "btn btn-info"
              %td= link_to 'Edit', edit_contact_path(contact), class: "btn btn-warning"
              %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

    %br

    = link_to 'New Contact', new_contact_path, class: "btn btn-default"
  %div.col-md-2

app/views/contacts/new.html.haml
%div.col-md-4
%div.col-md-4
  %h1 New contact

  = render 'form'

  = link_to 'Back', contacts_path, class: "btn btn-default"
%div.col-md-4

app/views/contacts/show.html.haml
%div.row
  %div.col-md-12
    %div.col-md-4
    %div.col-md-4
      %p
        = image_tag @contact.avatar.url(:medium)
      %p
        %b Name:
        = @contact.name
      %p
        %b Last name:
        = @contact.last_name
      %p
        %b Email:
        = @contact.email
      %p
        %b Contact type:
        = @contact.family
        = @contact.friends
        = @contact.coworker
      %p
        %b User:
        = @contact.user.id
      %p
        - @contact.phone_numbers.each do |p|
          %td= p.phone

      = link_to 'Edit', edit_contact_path(@contact), class: "btn btn-default"
      \|
      = link_to 'Back', contacts_path, class: "btn btn-default"
    %div.col-md-4